### ISSUE TITLE
CARD Short Name signification (SPECIES_GENE_ANTIBIOTIC Vs GENE)

### ISSUE THREAD

**Issue by AnisMansouri** [arpcard/amr_curation#102]
Hello,

I'd like to extract all E coli's resistant genes from CARD. I used `grep "Ecol_" aro.tsv` and I got 55 genes/RNAs. However, when I checked the aro.csv file I found other E coli AMR genes, e.g. baeS, but without the prefix "Ecol_ ". Should I also consider those genes? What is the difference between "SPECIES_GENE_DRUG" and "GENE" according to CARD Short Name rules?

Thank you,

**Comment by bpalcock** [comment]
Apologies for the very late reply! Typically, the `SPECIES_GENE_DRUG` format is only applied when resistance is determined by a set of mutations rather than the gene/enzyme itself. For example, beta-lactamase enzymes do not use `SPECIES_GENE_DRUG` but rather just `GENE` as you pointed out. This is because resistance-associated mutations can also be organism-specific. However, baeSR is a case where baeSR _does_ include resistance-associated mutations but is also unique (as far as I know) to _E. coli_. I think I'd agree that this is actually unclear and terms like baeSR should have CARD shortnames in the `SPECIES_GENE_DRUG` format, so I will discuss with the rest of the curation team.
