### ISSUE TITLE
Tet(47)-(56) listed as RPPs but are inactivating enzymes

### ISSUE THREAD

**Issue by kevinsblake** [arpcard/amr_curation#43]
Tet(47)-(56) ([PMID 26097034](https://www.ncbi.nlm.nih.gov/pubmed/26097034)) are currently listed under the @arpcard AMR Gene Family "[tetracycline-resistant ribosomal protection protein](https://card.mcmaster.ca/ontology/35921)," with a resistance mechanism of "antibiotic target protection". They should instead be under "tetracycline inactivation enzyme," with a resistance mechanism of "antibiotic inactivation."

Additionally, the definitions for Tet(48-56) should be edited to reflect the above (i.e. cut the sentence "A tetracycline-resistant ribosomal protection protein."). Further, the tet(47) entry should be edited such that 1) its definition matches the now edited versions of Tet(48-56), and 2) it is not be listed as a synonym of tet(57).

**Comment by huynhw1** [comment]
Hello @kevinsblake,

I've taken a look at tet(47)-tet(56). I have changed the parent classification to Tetracycline Inactivating Enzyme and changed the description to match accordingly.

As for tet(47), checking with Marilyn Roberts website at https://faculty.washington.edu/marilynr/,
it would seem that you are correct in that tet(57) is not a synonym. I have changed the parent classification, description and synonym to reflect this accordingly.

According to NCBI, tet(47) is a synonym for tet(57) going so far as to have the same sequence and classification as an MFS Transporter. Another entry in NCBI has tet(47) listed as a destructase, which lines up with Marilyn Roberts classification.

I'm not sure what to make of the tet(57) and tet(47) being MFS Transporters on NCBI, but that explains why tet(57) was listed as a synonym and tet(47) was misclassified. Additionally, because tet(57) is no longer listed as a synonym, I've added a new ontology on CARD for tet(57).

Thank you for pointing this out!

-------

William Huynh, CARD Curator-Developer

**Comment by kevinsblake** [comment]
Thank you @huynhw1 for addressing this so quickly! 
My guess is that tet(57) was originally published and reported on NCBI as tet(47), but then they changed the name when they saw the destructase paper--published in the same year, 2015--but the original tet(47) efflux NCBI entry remained. But that's just a guess.
As a head's up, I'd bet there's going to be a similar issue with tet(X6). Two groups published on tet(X6) within a month of each other (PMID [32068864](https://www.ncbi.nlm.nih.gov/pubmed/32068864) and [32016288](https://www.ncbi.nlm.nih.gov/pubmed/32016288)). Last I checked, they don't have NCBI entries yet, but they appear to be different proteins.
