### ISSUE TITLE
a confusion about aro.obo file 

### ISSUE THREAD

**Issue by feihongloveworld** [arpcard/amr_curation#48]
hi sir:
     when i parsing the aro.obo file from Ontology, there is a Questionable relationship as below：
‘’‘
[Term]
id: ARO:3004204
name: EBR beta-lactamase
namespace: antibiotic_resistance
def: "EBR beta-lactamases are Class B beta-lactamases first isolated from Empedobacter brevis and are able to hydrolyze penicillins, cephalosporins, and carbapenems." [PMID:12234848]
is_a: ARO:0000020 ! carbapenem
is_a: ARO:0000032 ! cephalosporin
is_a: ARO:3000008 ! penam
is_a: ARO:3000568 ! subclass B1 (metallo-) beta-lactamase
‘’’
the  “EBR beta-lactamase” shoud not be a penam

**Comment by arpcard** [comment]
Hello @feihongloveworld ,

Please use the latest CARD ontology from the CARD website.
I am looking at EBR-1 on my end and I only see "is_a: ARO:3004204 ! EBR beta-lactamase".
The issue was most likely fixed if you are using an outdated version.

All the best.

-----

William Huynh, CARD Curator-Developer
