### ISSUE TITLE
why was emrD discarded in current database ?

### ISSUE THREAD

**Issue by feihongloveworld** [arpcard/amr_curation#51]
hi @arpcard ：
     why was emrD discarded in current database ?
thanks

**Comment by huynhw1** [comment]
Hello @feihongloveworld ,

emrD is marked private on CARD because it is one of the models we have that we have concluded did not have sufficient MIC data to back its status as a resistance gene.

If you can source a paper that provides MIC values detailing its resistance activity, we would be glad to add it back.

Thank you.

**Comment by feihongloveworld** [comment]
thanks
