### ISSUE TITLE
Concerns about the bitscore of the detection model

### ISSUE THREAD

**Issue by Sebdu132** [arpcard/amr_curation#60]
Dear CARD team,

when looking at the mphB prevalence in the main bacterial pathogens (calculated using the CARD detection model and displayed on the mphB page), I noticed that this gene was detected in more than 95% of the Shigella complete chromosomes. When looking in more details, for instance in the genome NC_007606.1_chromosome, the CARD interface says that mphB was detected at 96% identity over 85% of the mphB reference.

However, when searching for mphB in Shigella genomes (including NC_007606) on the NCBI Microbial blast genome interface, only a distantly related gene (55% aa identity) comes out.

There is obviously a critical discrepancy here, which could be related to the bitscore threshold, but I can't understand why. My observation makes the whole results of the resistome analyses very untrustworthy to me.
Do you have any explanation ?

All the best.

**Comment by agmcarthur** [comment]
Thanks for your message. In the previous version of CARD's curated data (3.0.8) that was used to generate the Prevalence, Resistomes, & Variants predictions, there was a curation error for the protein sequence for mphB, leading to erroneous RGI predictions. This was corrected in the latest version of CARD curated data (3.1.0; https://card.mcmaster.ca/ontology/36457) but given the computational intensity required, the Prevalence, Resistomes, & Variants data always lags behind the core CARD curation and we have been slower than usual due to COVID-19 challenges to research. The next Prevalence, Resistomes, & Variants release is slated for January 2021 and these erroneous mphB prevalence predictions will not occur given the corrected sequence.
