### ISSUE TITLE
fabG1 mutation in card web, but not in card.json?

### ISSUE THREAD

**Issue by feihongloveworld** [arpcard/amr_curation#61]
hi sir:
       fabG1 mutation is a very important event in Mycobacterium tuberculosis Resistance，but not in card.json，so RGI will not work on this gene?

**Comment by arpcard** [comment]
Hi Fei, could you send me the name or ID of the exact term you're referring to? I believe the reason for this is because the mutations for this gene in CARD are either insertions or deletions, and RGI is not currently configured to use those mutations in resistance prediction, so they are excluded from the JSON. 

- Brian

**Comment by arpcard** [comment]
I will close this issue but additionally comment that there was a previous major update to Mtb mutation data in CARD so this may be addressed, again reminding that indels and other non-SNP type mutations are not currently supported by RGI
