### ISSUE TITLE
Klebsiella pneumoniae KpnEF - wrong efflux family?

### ISSUE THREAD

**Issue by dannagifford** [arpcard/amr_curation#65]
Klebsiella pneumoniae KpnEF is annotated as being an **MFS** family efflux pump. However, the citation given in the "Publications" box associated with the item says it's an **SMR** family efflux pump (it's in the title of the paper).

Can this be reconciled?

Klebsiella pneumoniae KpnEF:
https://card.mcmaster.ca/ontology/42515

**Comment by danielhhaft** [comment]
Daniel Haft from NCBI here, looking in.

Yes, we have our version of KpnE from CARD, BAH63251.1, annotated as "multidrug efflux SMR transporter subunit KpnE" after our review.

CARD has ARO:3004580 (Kpne_KpnE) assigned to "major facilitator superfamily (MFS) antibiotic efflux pump" (ARO:0010002) as the gene family instead of small multidrug resistance (SMR) antibiotic efflux pump (ARO:0010003)

and this assignment is not supported by homology.

Same error with BAH63252.1, ARO:3004583, assigned by mistake to MFS when it is really SMR.  

PMID: 23836167   says homologous to ebrAB, and that's correct.  

Please reclassify KpnE and KpnF (homologous subunits) as belonging to the SMR family.

**Comment by arpcard** [comment]
Hi Danna and Dan, I have gone ahead and made this change to KpnEF, it will be reflected in the next CARD release.
