### ISSUE TITLE
What happened with the MdsABC operon sequences from S. enterica in the protein homolog database?

### ISSUE THREAD

**Issue by nicoox45** [arpcard/amr_curation#68]
Hi, 

I was comparing some results from my custom Blast search against the protein homolog database (downloaded on May 9, 2021) and the RGI, and could notice that I was missing some results in the RGI. So, I checked CARD's updated database and couldn't find any of these three genes. 

And I was wondering if you have any strategy for operons implemented in the RGI. Does RGI differentiate between operons and only show the name of the operon or does it individually show each of the genes that were found from the blast search?

**Comment by smithk63** [comment]
Hello,

Currently, RGI only identifies individual genes and their variants in a given sequence. This is because it relies heavily on the ontological framework established by the CARD, which does not treat operons as individual entities. It is possible that future development of RGI could lead to the implementation of operon and protein complex groupings, but there is no strategy in place at the moment. You can find documentation on RGI at the [RGI GitHub page](https://github.com/arpcard/rgi). Furthermore, if you are finding that certain genes are missing from the CARD, you are welcome to submit them to us for curation, and they should be added for the next release.

Thank you,

Keaton Smith
Developer Assistant Co-op Student
CARD Junior Curator & Help Desk
