### ISSUE TITLE
CARD ARO:3007060 lists S595G, possibly invalid inclusion

### ISSUE THREAD

**Issue by SJohnsonMayo** [arpcard/amr_curation#76]
Hi all,

This is referring to the entry for Helicobacter pylori pbp1 mutants conferring resistance to amoxicillin (ARO:3007060) https://card.mcmaster.ca/ontology/45621 

We see a G595S variant citing PMID 17951983. We also see a S595G variant citing PMID  35114945. I believe the latter is a mistake. Browsing through the paper, the authors call the variant at this position G595S as well.

**Comment by smithk63** [comment]
Hello,

Thanks for letting us know! This does look like a curation mistake, since the wild type sequence possesses a glycine at position 595. Additionally, it looks like there may be some errors in the curation of other mutations from this paper. A CARD update is currently underway, however these issues will be corrected for the following release.
Thank you!

Keaton Smith
Developer Assistant Co-op Student
CARD Junior Curator & Help Desk

**Comment by smithk63** [comment]
Quick update: the G959S mutation was correct as you said. The other mutations from the paper cited for S959G were actually insertion mutations that had been incorrectly curated as substitutions. The mutations for this entry have been corrected and will be visible after our next release.

Best!
Keaton
