### ISSUE TITLE
Is OXA-1 a carbapenamase?

### ISSUE THREAD

**Issue by flashton2003** [arpcard/amr_curation#86]
Hello,

I'm not very familiar with CARD, and I'm not an AMR expert, so I could be misinterpreting things here.

However, OXA-1 seems to be called as a carbapenemase in CARD - https://card.mcmaster.ca/ontology/37796

But, from what I can read, OXA-1 isn't a carbapenemase? https://academic.oup.com/jac/article/74/2/326/5156209

Am I getting something wrong here?

Thanks,

Phil

**Comment by arpcard** [comment]
Hi Phil, you are correct that OXA-1 is not a carbapenemase - what's going on here is the way CARD handles `confers_resistance_to_drug_class` is based on _any_ member of the AMR Gene Family (in this case OXA beta-lactamases https://card.mcmaster.ca/ontology/36026). However this is still confusing on our part because it would be more correct to say _some_ OXA beta-lactamases `confer resistance to drug class` carbapenem (as is the case with OXA-23 for example).

The good news is your question has prompted a discussion among the curation team on how to better define and show this in CARD and we believe we have a good solution. The bad news is it will take some time to implement and so won't be ready in time for our next release. I suspect it will be introduced in the following release some time before the end of the year.

Thanks for bringing this to our attention!
- Brian

**Comment by bpalcock** [comment]
Hi Phil, just to let you know the most recent release of CARD completed this past month includes the changes to the OXA beta-lactamase ontology that should fix this issue

thanks
Brian

**Comment by flashton2003** [comment]
Great! Thanks Brian!
